/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author VicDellaSala
 */
public class InterfaceView extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public InterfaceView() {
        initComponents();
        this.setVisible(true);
    }
    
    private void enterConfigData() {
        simulationDuration.setText((String) Main.initialDataNick.getSimulationDuration());
        deadline.setText((String) Main.initialDataNick.getDeadline());
        screenwriters.setText((String) Main.initialDataNick.getScreenwriters());
        stageDesigner.setText((String) Main.initialDataNick.getStageDesigner());
        animator.setText((String) Main.initialDataNick.getAnimator());
        voiceActors.setText((String) Main.initialDataNick.getVoiceActors());
        plotTwistScriptwriters.setText((String) Main.initialDataNick.getPlotTwistScriptwriters());
        assemblers.setText((String) Main.initialDataNick.getAssemblers());
    }

    private void enterConfigData1() {
        simulationDuration1.setText((String) Main.initialDataStar.getSimulationDuration());
        deadline1.setText((String) Main.initialDataStar.getDeadline());
        screenwriters1.setText((String) Main.initialDataStar.getScreenwriters());
        stageDesigner1.setText((String) Main.initialDataStar.getStageDesigner());
        animator1.setText((String) Main.initialDataStar.getAnimator());
        voiceActors1.setText((String) Main.initialDataStar.getVoiceActors());
        plotTwistScriptwriters1.setText((String) Main.initialDataStar.getPlotTwistScriptwriters());
        assemblers1.setText((String) Main.initialDataStar.getAssemblers());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Ganancias = new javax.swing.JLabel();
        Costos = new javax.swing.JLabel();
        Utilidades = new javax.swing.JLabel();
        Giones = new javax.swing.JLabel();
        Escenarios = new javax.swing.JLabel();
        Animaciones = new javax.swing.JLabel();
        Doblajes = new javax.swing.JLabel();
        Drive = new javax.swing.JLabel();
        PlotTwist = new javax.swing.JLabel();
        ParaEntregar = new javax.swing.JLabel();
        Estandar = new javax.swing.JLabel();
        Plot = new javax.swing.JLabel();
        standard = new javax.swing.JLabel();
        plottwist = new javax.swing.JLabel();
        Supervision = new javax.swing.JLabel();
        Project = new javax.swing.JLabel();
        projectStatus = new javax.swing.JLabel();
        Director = new javax.swing.JLabel();
        directorStatus = new javax.swing.JLabel();
        Faltas = new javax.swing.JLabel();
        projectFaults = new javax.swing.JLabel();
        Descuento = new javax.swing.JLabel();
        projectManagerDeductionStar = new javax.swing.JLabel();
        DiasRestantes = new javax.swing.JLabel();
        deadlineCounter = new javax.swing.JLabel();
        Finanzas = new javax.swing.JLabel();
        plotStorage = new javax.swing.JLabel();
        spriptStorage = new javax.swing.JLabel();
        designerStorage = new javax.swing.JLabel();
        animatorStorage = new javax.swing.JLabel();
        dubbingStorage = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        earnings = new javax.swing.JLabel();
        costs = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simulationDuration = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        deadline = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        screenwriters = new javax.swing.JTextField();
        stageDesigner = new javax.swing.JTextField();
        animator = new javax.swing.JTextField();
        voiceActors = new javax.swing.JTextField();
        plotTwistScriptwriters = new javax.swing.JTextField();
        assemblers = new javax.swing.JTextField();
        saveButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        projectManagerDeduction = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Ganancias1 = new javax.swing.JLabel();
        Costos1 = new javax.swing.JLabel();
        Utilidades1 = new javax.swing.JLabel();
        Giones1 = new javax.swing.JLabel();
        Escenarios1 = new javax.swing.JLabel();
        Animaciones1 = new javax.swing.JLabel();
        Doblajes1 = new javax.swing.JLabel();
        Drive1 = new javax.swing.JLabel();
        PlotTwist1 = new javax.swing.JLabel();
        ParaEntregar1 = new javax.swing.JLabel();
        Estandar1 = new javax.swing.JLabel();
        Plot1 = new javax.swing.JLabel();
        standardStar1 = new javax.swing.JLabel();
        plottwistStar1 = new javax.swing.JLabel();
        Supervision1 = new javax.swing.JLabel();
        Project1 = new javax.swing.JLabel();
        projectStatusStar1 = new javax.swing.JLabel();
        Director1 = new javax.swing.JLabel();
        directorStatusStar1 = new javax.swing.JLabel();
        Faltas1 = new javax.swing.JLabel();
        projectFaultsStar1 = new javax.swing.JLabel();
        Descuento1 = new javax.swing.JLabel();
        projectManagerDeductionStar1 = new javax.swing.JLabel();
        DiasRestantes1 = new javax.swing.JLabel();
        deadlineCounterStar1 = new javax.swing.JLabel();
        Finanzas1 = new javax.swing.JLabel();
        plotStorageStar = new javax.swing.JLabel();
        spriptStorageStar = new javax.swing.JLabel();
        designerStorageStar = new javax.swing.JLabel();
        animatorStorageStar = new javax.swing.JLabel();
        dubbingStorageStar = new javax.swing.JLabel();
        profitStar = new javax.swing.JLabel();
        costsStar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        simulationDuration1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        deadline1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        screenwriters1 = new javax.swing.JTextField();
        stageDesigner1 = new javax.swing.JTextField();
        animator1 = new javax.swing.JTextField();
        voiceActors1 = new javax.swing.JTextField();
        plotTwistScriptwriters1 = new javax.swing.JTextField();
        assemblers1 = new javax.swing.JTextField();
        saveButton2 = new javax.swing.JButton();
        earningsStar = new javax.swing.JLabel();
        SimpsonsText = new javax.swing.JLabel();
        MargeSimpson = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ganancias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ganancias.setText("Ganancias:");
        jPanel1.add(Ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        Costos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Costos.setText("Costos:");
        jPanel1.add(Costos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        Utilidades.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Utilidades.setText("Utilidades:");
        jPanel1.add(Utilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        Giones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Giones.setText("Guiones:");
        jPanel1.add(Giones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        Escenarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Escenarios.setText("Escenarios:");
        jPanel1.add(Escenarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        Animaciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Animaciones.setText("Animaciones:");
        jPanel1.add(Animaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        Doblajes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Doblajes.setText("Doblajes:");
        jPanel1.add(Doblajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        Drive.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Drive.setText("Drive");
        jPanel1.add(Drive, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        PlotTwist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlotTwist.setText("PlotTwist:");
        jPanel1.add(PlotTwist, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        ParaEntregar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ParaEntregar.setText("Capítulos a Entregar");
        jPanel1.add(ParaEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        Estandar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Estandar.setText("Estándar:");
        jPanel1.add(Estandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        Plot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plot.setText("PlotTwist:");
        jPanel1.add(Plot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        standard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        standard.setText("0");
        standard.setToolTipText("");
        jPanel1.add(standard, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 70, -1));

        plottwist.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plottwist.setText("0");
        jPanel1.add(plottwist, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 70, -1));

        Supervision.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Supervision.setText("Supervisión");
        jPanel1.add(Supervision, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        Project.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Project.setText("Project Manager:");
        jPanel1.add(Project, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        projectStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectStatus.setText("status");
        jPanel1.add(projectStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, -1, -1));

        Director.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Director.setText("Director:");
        jPanel1.add(Director, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        directorStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        directorStatus.setText("status");
        jPanel1.add(directorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        Faltas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Faltas.setText("Faltas");
        jPanel1.add(Faltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        projectFaults.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectFaults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectFaults.setText("0");
        jPanel1.add(projectFaults, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 70, -1));

        Descuento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Descuento.setText("Descuento");
        jPanel1.add(Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, -1, -1));

        projectManagerDeductionStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectManagerDeductionStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectManagerDeductionStar.setText("0");
        jPanel1.add(projectManagerDeductionStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 210, -1));

        DiasRestantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DiasRestantes.setText("Días restantes:");
        jPanel1.add(DiasRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        deadlineCounter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deadlineCounter.setText("0");
        jPanel1.add(deadlineCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 60, -1));

        Finanzas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Finanzas.setText("Nickelodeon");
        jPanel1.add(Finanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        plotStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plotStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        plotStorage.setText("/10");
        jPanel1.add(plotStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 90, -1));

        spriptStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spriptStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spriptStorage.setText("/25");
        jPanel1.add(spriptStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, -1));

        designerStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        designerStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        designerStorage.setText("/20");
        jPanel1.add(designerStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, -1));

        animatorStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        animatorStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        animatorStorage.setText("/55");
        jPanel1.add(animatorStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, -1));

        dubbingStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dubbingStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dubbingStorage.setText("/35");
        jPanel1.add(dubbingStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 90, -1));

        profit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profit.setText("0");
        jPanel1.add(profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 240, -1));

        earnings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        earnings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        earnings.setText("0");
        jPanel1.add(earnings, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 250, -1));

        costs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        costs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        costs.setText("0");
        jPanel1.add(costs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 260, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Duración de un día (segundos)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));
        jPanel1.add(simulationDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 71, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Deadline de los capítulos (días):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));
        jPanel1.add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 71, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Trabajadores:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Guionistas:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Diseñador de escenarios:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Animador de personajes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Actores de doblaje:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("PlotTwist:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Ensambladores:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));
        jPanel1.add(screenwriters, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 71, -1));
        jPanel1.add(stageDesigner, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 71, -1));
        jPanel1.add(animator, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 71, -1));
        jPanel1.add(voiceActors, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 71, -1));
        jPanel1.add(plotTwistScriptwriters, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 71, -1));
        jPanel1.add(assemblers, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 71, -1));

        saveButton1.setText("Guardar");
        jPanel1.add(saveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Timmy_Turner3.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        projectManagerDeduction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nickpng.png"))); // NOI18N
        jPanel1.add(projectManagerDeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -320, 1180, 950));

        jTabbedPane1.addTab("Nickelodeon", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 250, 58));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ganancias1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ganancias1.setText("Ganancias:");
        jPanel2.add(Ganancias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        Costos1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Costos1.setText("Costos:");
        jPanel2.add(Costos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        Utilidades1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Utilidades1.setText("Utilidades:");
        jPanel2.add(Utilidades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        Giones1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Giones1.setText("Guiones:");
        jPanel2.add(Giones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        Escenarios1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Escenarios1.setText("Escenarios:");
        jPanel2.add(Escenarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        Animaciones1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Animaciones1.setText("Animaciones:");
        jPanel2.add(Animaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        Doblajes1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Doblajes1.setText("Doblajes:");
        jPanel2.add(Doblajes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        Drive1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Drive1.setText("Drive");
        jPanel2.add(Drive1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        PlotTwist1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlotTwist1.setText("PlotTwist:");
        jPanel2.add(PlotTwist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        ParaEntregar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ParaEntregar1.setText("Capítulos a Entregar");
        jPanel2.add(ParaEntregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        Estandar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Estandar1.setText("Estándar:");
        jPanel2.add(Estandar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        Plot1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plot1.setText("PlotTwist:");
        jPanel2.add(Plot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        standardStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        standardStar1.setText("0");
        standardStar1.setToolTipText("");
        jPanel2.add(standardStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 70, -1));

        plottwistStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plottwistStar1.setText("0");
        jPanel2.add(plottwistStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 70, -1));

        Supervision1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Supervision1.setText("Supervisión");
        jPanel2.add(Supervision1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        Project1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Project1.setText("Project Manager:");
        jPanel2.add(Project1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        projectStatusStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectStatusStar1.setText("status");
        jPanel2.add(projectStatusStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, -1, -1));

        Director1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Director1.setText("Director:");
        jPanel2.add(Director1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        directorStatusStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        directorStatusStar1.setText("status");
        jPanel2.add(directorStatusStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        Faltas1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Faltas1.setText("Faltas");
        jPanel2.add(Faltas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        projectFaultsStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectFaultsStar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectFaultsStar1.setText("0");
        jPanel2.add(projectFaultsStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 70, -1));

        Descuento1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Descuento1.setText("Descuento");
        jPanel2.add(Descuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, -1, -1));

        projectManagerDeductionStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectManagerDeductionStar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectManagerDeductionStar1.setText("0");
        jPanel2.add(projectManagerDeductionStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 210, -1));

        DiasRestantes1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DiasRestantes1.setText("Días restantes:");
        jPanel2.add(DiasRestantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        deadlineCounterStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deadlineCounterStar1.setText("0");
        jPanel2.add(deadlineCounterStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 60, -1));

        Finanzas1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Finanzas1.setText("Star Channel");
        jPanel2.add(Finanzas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        plotStorageStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plotStorageStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        plotStorageStar.setText("/10");
        jPanel2.add(plotStorageStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 90, -1));

        spriptStorageStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spriptStorageStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spriptStorageStar.setText("/25");
        jPanel2.add(spriptStorageStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, -1));

        designerStorageStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        designerStorageStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        designerStorageStar.setText("/20");
        jPanel2.add(designerStorageStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, -1));

        animatorStorageStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        animatorStorageStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        animatorStorageStar.setText("/55");
        jPanel2.add(animatorStorageStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, -1));

        dubbingStorageStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dubbingStorageStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dubbingStorageStar.setText("/35");
        jPanel2.add(dubbingStorageStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 90, -1));

        profitStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profitStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profitStar.setText("0");
        jPanel2.add(profitStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 240, -1));

        costsStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        costsStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        costsStar.setText("0");
        jPanel2.add(costsStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 250, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Duración de un día (segundos)");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));
        jPanel2.add(simulationDuration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 71, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Deadline de los capítulos (días):");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));
        jPanel2.add(deadline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 71, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Trabajadores:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Guionistas:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Diseñador de escenarios:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Animador de personajes:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Actores de doblaje:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("PlotTwist:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Ensambladores:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));
        jPanel2.add(screenwriters1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 71, -1));
        jPanel2.add(stageDesigner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 71, -1));
        jPanel2.add(animator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 71, -1));
        jPanel2.add(voiceActors1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 71, -1));
        jPanel2.add(plotTwistScriptwriters1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 71, -1));
        jPanel2.add(assemblers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 71, -1));

        saveButton2.setText("Guardar");
        jPanel2.add(saveButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, -1, -1));

        earningsStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        earningsStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        earningsStar.setText("0");
        jPanel2.add(earningsStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 250, -1));

        SimpsonsText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image1.png"))); // NOI18N
        jPanel2.add(SimpsonsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        MargeSimpson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/star-header-2.png"))); // NOI18N
        jPanel2.add(MargeSimpson, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -90, 1180, 640));

        jTabbedPane1.addTab("Star Channel", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1179, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getAnimaciones() {
        return Animaciones;
    }

    public void setAnimaciones(JLabel Animaciones) {
        this.Animaciones = Animaciones;
    }

    public JLabel getAnimaciones1() {
        return Animaciones1;
    }

    public void setAnimaciones1(JLabel Animaciones1) {
        this.Animaciones1 = Animaciones1;
    }

    public JLabel getCostos() {
        return Costos;
    }

    public void setCostos(JLabel Costos) {
        this.Costos = Costos;
    }

    public JLabel getCostos1() {
        return Costos1;
    }

    public void setCostos1(JLabel Costos1) {
        this.Costos1 = Costos1;
    }

    public JLabel getDescuento() {
        return Descuento;
    }

    public void setDescuento(JLabel Descuento) {
        this.Descuento = Descuento;
    }

    public JLabel getDescuento1() {
        return Descuento1;
    }

    public void setDescuento1(JLabel Descuento1) {
        this.Descuento1 = Descuento1;
    }

    public JLabel getDiasRestantes() {
        return DiasRestantes;
    }

    public void setDiasRestantes(JLabel DiasRestantes) {
        this.DiasRestantes = DiasRestantes;
    }

    public JLabel getDiasRestantes1() {
        return DiasRestantes1;
    }

    public void setDiasRestantes1(JLabel DiasRestantes1) {
        this.DiasRestantes1 = DiasRestantes1;
    }

    public JLabel getDirector() {
        return Director;
    }

    public void setDirector(JLabel Director) {
        this.Director = Director;
    }

    public JLabel getDirector1() {
        return Director1;
    }

    public void setDirector1(JLabel Director1) {
        this.Director1 = Director1;
    }

    public JLabel getDoblajes() {
        return Doblajes;
    }

    public void setDoblajes(JLabel Doblajes) {
        this.Doblajes = Doblajes;
    }

    public JLabel getDoblajes1() {
        return Doblajes1;
    }

    public void setDoblajes1(JLabel Doblajes1) {
        this.Doblajes1 = Doblajes1;
    }

    public JLabel getDrive() {
        return Drive;
    }

    public void setDrive(JLabel Drive) {
        this.Drive = Drive;
    }

    public JLabel getDrive1() {
        return Drive1;
    }

    public void setDrive1(JLabel Drive1) {
        this.Drive1 = Drive1;
    }

    public JLabel getEscenarios() {
        return Escenarios;
    }

    public void setEscenarios(JLabel Escenarios) {
        this.Escenarios = Escenarios;
    }

    public JLabel getEscenarios1() {
        return Escenarios1;
    }

    public void setEscenarios1(JLabel Escenarios1) {
        this.Escenarios1 = Escenarios1;
    }

    public JLabel getEstandar() {
        return Estandar;
    }

    public void setEstandar(JLabel Estandar) {
        this.Estandar = Estandar;
    }

    public JLabel getEstandar1() {
        return Estandar1;
    }

    public void setEstandar1(JLabel Estandar1) {
        this.Estandar1 = Estandar1;
    }

    public JLabel getFaltas() {
        return Faltas;
    }

    public void setFaltas(JLabel Faltas) {
        this.Faltas = Faltas;
    }

    public JLabel getFaltas1() {
        return Faltas1;
    }

    public void setFaltas1(JLabel Faltas1) {
        this.Faltas1 = Faltas1;
    }

    public JLabel getFinanzas() {
        return Finanzas;
    }

    public void setFinanzas(JLabel Finanzas) {
        this.Finanzas = Finanzas;
    }

    public JLabel getFinanzas1() {
        return Finanzas1;
    }

    public void setFinanzas1(JLabel Finanzas1) {
        this.Finanzas1 = Finanzas1;
    }

    public JLabel getGanancias() {
        return Ganancias;
    }

    public void setGanancias(JLabel Ganancias) {
        this.Ganancias = Ganancias;
    }

    public JLabel getGanancias1() {
        return Ganancias1;
    }

    public void setGanancias1(JLabel Ganancias1) {
        this.Ganancias1 = Ganancias1;
    }

    public JLabel getGiones() {
        return Giones;
    }

    public void setGiones(JLabel Giones) {
        this.Giones = Giones;
    }

    public JLabel getGiones1() {
        return Giones1;
    }

    public void setGiones1(JLabel Giones1) {
        this.Giones1 = Giones1;
    }

    public JLabel getMargeSimpson() {
        return MargeSimpson;
    }

    public void setMargeSimpson(JLabel MargeSimpson) {
        this.MargeSimpson = MargeSimpson;
    }

    public JLabel getParaEntregar() {
        return ParaEntregar;
    }

    public void setParaEntregar(JLabel ParaEntregar) {
        this.ParaEntregar = ParaEntregar;
    }

    public JLabel getParaEntregar1() {
        return ParaEntregar1;
    }

    public void setParaEntregar1(JLabel ParaEntregar1) {
        this.ParaEntregar1 = ParaEntregar1;
    }

    public JLabel getPlot() {
        return Plot;
    }

    public void setPlot(JLabel Plot) {
        this.Plot = Plot;
    }

    public JLabel getPlot1() {
        return Plot1;
    }

    public void setPlot1(JLabel Plot1) {
        this.Plot1 = Plot1;
    }

    public JLabel getPlotTwist() {
        return PlotTwist;
    }

    public void setPlotTwist(JLabel PlotTwist) {
        this.PlotTwist = PlotTwist;
    }

    public JLabel getPlotTwist1() {
        return PlotTwist1;
    }

    public void setPlotTwist1(JLabel PlotTwist1) {
        this.PlotTwist1 = PlotTwist1;
    }

    public JLabel getProject() {
        return Project;
    }

    public void setProject(JLabel Project) {
        this.Project = Project;
    }

    public JLabel getProject1() {
        return Project1;
    }

    public void setProject1(JLabel Project1) {
        this.Project1 = Project1;
    }

    public JLabel getSimpsonsText() {
        return SimpsonsText;
    }

    public void setSimpsonsText(JLabel SimpsonsText) {
        this.SimpsonsText = SimpsonsText;
    }

    public JLabel getSupervision() {
        return Supervision;
    }

    public void setSupervision(JLabel Supervision) {
        this.Supervision = Supervision;
    }

    public JLabel getSupervision1() {
        return Supervision1;
    }

    public void setSupervision1(JLabel Supervision1) {
        this.Supervision1 = Supervision1;
    }

    public JLabel getUtilidades() {
        return Utilidades;
    }

    public void setUtilidades(JLabel Utilidades) {
        this.Utilidades = Utilidades;
    }

    public JLabel getUtilidades1() {
        return Utilidades1;
    }

    public void setUtilidades1(JLabel Utilidades1) {
        this.Utilidades1 = Utilidades1;
    }

    public JTextField getAnimator() {
        return animator;
    }

    public void setAnimator(JTextField animator) {
        this.animator = animator;
    }

    public JTextField getAnimator1() {
        return animator1;
    }

    public void setAnimator1(JTextField animator1) {
        this.animator1 = animator1;
    }

    public JLabel getAnimatorStorage() {
        return animatorStorage;
    }

    public void setAnimatorStorage(JLabel animatorStorage) {
        this.animatorStorage = animatorStorage;
    }

    public JLabel getAnimatorStorageStar() {
        return animatorStorageStar;
    }

    public void setAnimatorStorageStar(JLabel animatorStorageStar) {
        this.animatorStorageStar = animatorStorageStar;
    }

    public JTextField getAssemblers() {
        return assemblers;
    }

    public void setAssemblers(JTextField assemblers) {
        this.assemblers = assemblers;
    }

    public JTextField getAssemblers1() {
        return assemblers1;
    }

    public void setAssemblers1(JTextField assemblers1) {
        this.assemblers1 = assemblers1;
    }

    public JLabel getCosts() {
        return costs;
    }

    public void setCosts(JLabel costs) {
        this.costs = costs;
    }

    public JLabel getCostsStar() {
        return costsStar;
    }

    public void setCostsStar(JLabel costsStar) {
        this.costsStar = costsStar;
    }

    public JTextField getDeadline() {
        return deadline;
    }

    public void setDeadline(JTextField deadline) {
        this.deadline = deadline;
    }

    public JTextField getDeadline1() {
        return deadline1;
    }

    public void setDeadline1(JTextField deadline1) {
        this.deadline1 = deadline1;
    }

    public JLabel getDeadlineCounter() {
        return deadlineCounter;
    }

    public void setDeadlineCounter(JLabel deadlineCounter) {
        this.deadlineCounter = deadlineCounter;
    }

    public JLabel getDeadlineCounterStar1() {
        return deadlineCounterStar1;
    }

    public void setDeadlineCounterStar1(JLabel deadlineCounterStar1) {
        this.deadlineCounterStar1 = deadlineCounterStar1;
    }

    public JLabel getDesignerStorage() {
        return designerStorage;
    }

    public void setDesignerStorage(JLabel designerStorage) {
        this.designerStorage = designerStorage;
    }

    public JLabel getDesignerStorageStar() {
        return designerStorageStar;
    }

    public void setDesignerStorageStar(JLabel designerStorageStar) {
        this.designerStorageStar = designerStorageStar;
    }

    public JLabel getDirectorStatus() {
        return directorStatus;
    }

    public void setDirectorStatus(JLabel directorStatus) {
        this.directorStatus = directorStatus;
    }

    public JLabel getDirectorStatusStar1() {
        return directorStatusStar1;
    }

    public void setDirectorStatusStar1(JLabel directorStatusStar1) {
        this.directorStatusStar1 = directorStatusStar1;
    }

    public JLabel getDubbingStorage() {
        return dubbingStorage;
    }

    public void setDubbingStorage(JLabel dubbingStorage) {
        this.dubbingStorage = dubbingStorage;
    }

    public JLabel getDubbingStorageStar() {
        return dubbingStorageStar;
    }

    public void setDubbingStorageStar(JLabel dubbingStorageStar) {
        this.dubbingStorageStar = dubbingStorageStar;
    }

    public JLabel getEarnings() {
        return earnings;
    }

    public void setEarnings(JLabel earnings) {
        this.earnings = earnings;
    }

    public JLabel getEarningsStar() {
        return earningsStar;
    }

    public void setEarningsStar(JLabel earningsStar) {
        this.earningsStar = earningsStar;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JLabel getPlotStorage() {
        return plotStorage;
    }

    public void setPlotStorage(JLabel plotStorage) {
        this.plotStorage = plotStorage;
    }

    public JLabel getPlotStorageStar() {
        return plotStorageStar;
    }

    public void setPlotStorageStar(JLabel plotStorageStar) {
        this.plotStorageStar = plotStorageStar;
    }

    public JTextField getPlotTwistScriptwriters() {
        return plotTwistScriptwriters;
    }

    public void setPlotTwistScriptwriters(JTextField plotTwistScriptwriters) {
        this.plotTwistScriptwriters = plotTwistScriptwriters;
    }

    public JTextField getPlotTwistScriptwriters1() {
        return plotTwistScriptwriters1;
    }

    public void setPlotTwistScriptwriters1(JTextField plotTwistScriptwriters1) {
        this.plotTwistScriptwriters1 = plotTwistScriptwriters1;
    }

    public JLabel getPlottwist() {
        return plottwist;
    }

    public void setPlottwist(JLabel plottwist) {
        this.plottwist = plottwist;
    }

    public JLabel getPlottwistStar1() {
        return plottwistStar1;
    }

    public void setPlottwistStar1(JLabel plottwistStar1) {
        this.plottwistStar1 = plottwistStar1;
    }

    public JLabel getProfit() {
        return profit;
    }

    public void setProfit(JLabel profit) {
        this.profit = profit;
    }

    public JLabel getProfitStar() {
        return profitStar;
    }

    public void setProfitStar(JLabel profitStar) {
        this.profitStar = profitStar;
    }

    public JLabel getProjectFaults() {
        return projectFaults;
    }

    public void setProjectFaults(JLabel projectFaults) {
        this.projectFaults = projectFaults;
    }

    public JLabel getProjectFaultsStar1() {
        return projectFaultsStar1;
    }

    public void setProjectFaultsStar1(JLabel projectFaultsStar1) {
        this.projectFaultsStar1 = projectFaultsStar1;
    }

    public JLabel getProjectManagerDeduction() {
        return projectManagerDeduction;
    }

    public void setProjectManagerDeduction(JLabel projectManagerDeduction) {
        this.projectManagerDeduction = projectManagerDeduction;
    }

    public JLabel getProjectManagerDeductionStar() {
        return projectManagerDeductionStar;
    }

    public void setProjectManagerDeductionStar(JLabel projectManagerDeductionStar) {
        this.projectManagerDeductionStar = projectManagerDeductionStar;
    }

    public JLabel getProjectManagerDeductionStar1() {
        return projectManagerDeductionStar1;
    }

    public void setProjectManagerDeductionStar1(JLabel projectManagerDeductionStar1) {
        this.projectManagerDeductionStar1 = projectManagerDeductionStar1;
    }

    public JLabel getProjectStatus() {
        return projectStatus;
    }

    public void setProjectStatus(JLabel projectStatus) {
        this.projectStatus = projectStatus;
    }

    public JLabel getProjectStatusStar1() {
        return projectStatusStar1;
    }

    public void setProjectStatusStar1(JLabel projectStatusStar1) {
        this.projectStatusStar1 = projectStatusStar1;
    }

    public JButton getSaveButton1() {
        return saveButton1;
    }

    public void setSaveButton1(JButton saveButton1) {
        this.saveButton1 = saveButton1;
    }

    public JButton getSaveButton2() {
        return saveButton2;
    }

    public void setSaveButton2(JButton saveButton2) {
        this.saveButton2 = saveButton2;
    }

    public JTextField getScreenwriters() {
        return screenwriters;
    }

    public void setScreenwriters(JTextField screenwriters) {
        this.screenwriters = screenwriters;
    }

    public JTextField getScreenwriters1() {
        return screenwriters1;
    }

    public void setScreenwriters1(JTextField screenwriters1) {
        this.screenwriters1 = screenwriters1;
    }

    public JTextField getSimulationDuration() {
        return simulationDuration;
    }

    public void setSimulationDuration(JTextField simulationDuration) {
        this.simulationDuration = simulationDuration;
    }

    public JTextField getSimulationDuration1() {
        return simulationDuration1;
    }

    public void setSimulationDuration1(JTextField simulationDuration1) {
        this.simulationDuration1 = simulationDuration1;
    }

    public JLabel getSpriptStorage() {
        return spriptStorage;
    }

    public void setSpriptStorage(JLabel spriptStorage) {
        this.spriptStorage = spriptStorage;
    }

    public JLabel getSpriptStorageStar() {
        return spriptStorageStar;
    }

    public void setSpriptStorageStar(JLabel spriptStorageStar) {
        this.spriptStorageStar = spriptStorageStar;
    }

    public JTextField getStageDesigner() {
        return stageDesigner;
    }

    public void setStageDesigner(JTextField stageDesigner) {
        this.stageDesigner = stageDesigner;
    }

    public JTextField getStageDesigner1() {
        return stageDesigner1;
    }

    public void setStageDesigner1(JTextField stageDesigner1) {
        this.stageDesigner1 = stageDesigner1;
    }

    public JLabel getStandard() {
        return standard;
    }

    public void setStandard(JLabel standard) {
        this.standard = standard;
    }

    public JLabel getStandardStar1() {
        return standardStar1;
    }

    public void setStandardStar1(JLabel standardStar1) {
        this.standardStar1 = standardStar1;
    }

    public JTextField getVoiceActors() {
        return voiceActors;
    }

    public void setVoiceActors(JTextField voiceActors) {
        this.voiceActors = voiceActors;
    }

    public JTextField getVoiceActors1() {
        return voiceActors1;
    }

    public void setVoiceActors1(JTextField voiceActors1) {
        this.voiceActors1 = voiceActors1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Animaciones;
    private javax.swing.JLabel Animaciones1;
    private javax.swing.JLabel Costos;
    private javax.swing.JLabel Costos1;
    private javax.swing.JLabel Descuento;
    private javax.swing.JLabel Descuento1;
    private javax.swing.JLabel DiasRestantes;
    private javax.swing.JLabel DiasRestantes1;
    private javax.swing.JLabel Director;
    private javax.swing.JLabel Director1;
    private javax.swing.JLabel Doblajes;
    private javax.swing.JLabel Doblajes1;
    private javax.swing.JLabel Drive;
    private javax.swing.JLabel Drive1;
    private javax.swing.JLabel Escenarios;
    private javax.swing.JLabel Escenarios1;
    private javax.swing.JLabel Estandar;
    private javax.swing.JLabel Estandar1;
    private javax.swing.JLabel Faltas;
    private javax.swing.JLabel Faltas1;
    private javax.swing.JLabel Finanzas;
    private javax.swing.JLabel Finanzas1;
    private javax.swing.JLabel Ganancias;
    private javax.swing.JLabel Ganancias1;
    private javax.swing.JLabel Giones;
    private javax.swing.JLabel Giones1;
    private javax.swing.JLabel MargeSimpson;
    private javax.swing.JLabel ParaEntregar;
    private javax.swing.JLabel ParaEntregar1;
    private javax.swing.JLabel Plot;
    private javax.swing.JLabel Plot1;
    private javax.swing.JLabel PlotTwist;
    private javax.swing.JLabel PlotTwist1;
    private javax.swing.JLabel Project;
    private javax.swing.JLabel Project1;
    private javax.swing.JLabel SimpsonsText;
    private javax.swing.JLabel Supervision;
    private javax.swing.JLabel Supervision1;
    private javax.swing.JLabel Utilidades;
    private javax.swing.JLabel Utilidades1;
    private javax.swing.JTextField animator;
    private javax.swing.JTextField animator1;
    private javax.swing.JLabel animatorStorage;
    private javax.swing.JLabel animatorStorageStar;
    private javax.swing.JTextField assemblers;
    private javax.swing.JTextField assemblers1;
    private javax.swing.JLabel costs;
    private javax.swing.JLabel costsStar;
    private javax.swing.JTextField deadline;
    private javax.swing.JTextField deadline1;
    private javax.swing.JLabel deadlineCounter;
    private javax.swing.JLabel deadlineCounterStar1;
    private javax.swing.JLabel designerStorage;
    private javax.swing.JLabel designerStorageStar;
    private javax.swing.JLabel directorStatus;
    private javax.swing.JLabel directorStatusStar1;
    private javax.swing.JLabel dubbingStorage;
    private javax.swing.JLabel dubbingStorageStar;
    private javax.swing.JLabel earnings;
    private javax.swing.JLabel earningsStar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel plotStorage;
    private javax.swing.JLabel plotStorageStar;
    private javax.swing.JTextField plotTwistScriptwriters;
    private javax.swing.JTextField plotTwistScriptwriters1;
    private javax.swing.JLabel plottwist;
    private javax.swing.JLabel plottwistStar1;
    private javax.swing.JLabel profit;
    private javax.swing.JLabel profitStar;
    private javax.swing.JLabel projectFaults;
    private javax.swing.JLabel projectFaultsStar1;
    private javax.swing.JLabel projectManagerDeduction;
    private javax.swing.JLabel projectManagerDeductionStar;
    private javax.swing.JLabel projectManagerDeductionStar1;
    private javax.swing.JLabel projectStatus;
    private javax.swing.JLabel projectStatusStar1;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton saveButton2;
    private javax.swing.JTextField screenwriters;
    private javax.swing.JTextField screenwriters1;
    private javax.swing.JTextField simulationDuration;
    private javax.swing.JTextField simulationDuration1;
    private javax.swing.JLabel spriptStorage;
    private javax.swing.JLabel spriptStorageStar;
    private javax.swing.JTextField stageDesigner;
    private javax.swing.JTextField stageDesigner1;
    private javax.swing.JLabel standard;
    private javax.swing.JLabel standardStar1;
    private javax.swing.JTextField voiceActors;
    private javax.swing.JTextField voiceActors1;
    // End of variables declaration//GEN-END:variables
}
