/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

/**
 *
 * @author VicDellaSala
 */
public class InterfaceView extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public InterfaceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Ganancias = new javax.swing.JLabel();
        Costos = new javax.swing.JLabel();
        Utilidades = new javax.swing.JLabel();
        Giones = new javax.swing.JLabel();
        Escenarios = new javax.swing.JLabel();
        Animaciones = new javax.swing.JLabel();
        Doblajes = new javax.swing.JLabel();
        Drive = new javax.swing.JLabel();
        PlotTwist = new javax.swing.JLabel();
        ParaEntregar = new javax.swing.JLabel();
        Estandar = new javax.swing.JLabel();
        Plot = new javax.swing.JLabel();
        standardStar = new javax.swing.JLabel();
        plottwistStar = new javax.swing.JLabel();
        Supervision = new javax.swing.JLabel();
        Project = new javax.swing.JLabel();
        projectStatusStar = new javax.swing.JLabel();
        Director = new javax.swing.JLabel();
        directorStatusStar = new javax.swing.JLabel();
        Faltas = new javax.swing.JLabel();
        projectFaultsStar = new javax.swing.JLabel();
        Descuento = new javax.swing.JLabel();
        projectManagerDeductionStar = new javax.swing.JLabel();
        DiasRestantes = new javax.swing.JLabel();
        deadlineCounterStar = new javax.swing.JLabel();
        Finanzas = new javax.swing.JLabel();
        plotStorage = new javax.swing.JLabel();
        spriptStorage = new javax.swing.JLabel();
        designerStorage = new javax.swing.JLabel();
        animatorStorage = new javax.swing.JLabel();
        dubbingStorage = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        earnings = new javax.swing.JLabel();
        costs = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simulationDuration = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        deadline = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        screenwriters = new javax.swing.JTextField();
        stageDesigner = new javax.swing.JTextField();
        animator = new javax.swing.JTextField();
        voiceActors = new javax.swing.JTextField();
        plotTwistScriptwriters = new javax.swing.JTextField();
        assemblers = new javax.swing.JTextField();
        saveButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Ganancias1 = new javax.swing.JLabel();
        Costos1 = new javax.swing.JLabel();
        Utilidades1 = new javax.swing.JLabel();
        Giones1 = new javax.swing.JLabel();
        Escenarios1 = new javax.swing.JLabel();
        Animaciones1 = new javax.swing.JLabel();
        Doblajes1 = new javax.swing.JLabel();
        Drive1 = new javax.swing.JLabel();
        PlotTwist1 = new javax.swing.JLabel();
        ParaEntregar1 = new javax.swing.JLabel();
        Estandar1 = new javax.swing.JLabel();
        Plot1 = new javax.swing.JLabel();
        standardStar1 = new javax.swing.JLabel();
        plottwistStar1 = new javax.swing.JLabel();
        Supervision1 = new javax.swing.JLabel();
        Project1 = new javax.swing.JLabel();
        projectStatusStar1 = new javax.swing.JLabel();
        Director1 = new javax.swing.JLabel();
        directorStatusStar1 = new javax.swing.JLabel();
        Faltas1 = new javax.swing.JLabel();
        projectFaultsStar1 = new javax.swing.JLabel();
        Descuento1 = new javax.swing.JLabel();
        projectManagerDeductionStar1 = new javax.swing.JLabel();
        DiasRestantes1 = new javax.swing.JLabel();
        deadlineCounterStar1 = new javax.swing.JLabel();
        Finanzas1 = new javax.swing.JLabel();
        plotStorage1 = new javax.swing.JLabel();
        spriptStorage1 = new javax.swing.JLabel();
        designerStorage1 = new javax.swing.JLabel();
        animatorStorage1 = new javax.swing.JLabel();
        dubbingStorage1 = new javax.swing.JLabel();
        profit1 = new javax.swing.JLabel();
        earnings1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        simulationDuration1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        deadline1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        screenwriters1 = new javax.swing.JTextField();
        stageDesigner1 = new javax.swing.JTextField();
        animator1 = new javax.swing.JTextField();
        voiceActors1 = new javax.swing.JTextField();
        plotTwistScriptwriters1 = new javax.swing.JTextField();
        assemblers1 = new javax.swing.JTextField();
        saveButton2 = new javax.swing.JButton();
        SimpsonsText = new javax.swing.JLabel();
        MargeSimpson = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ganancias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ganancias.setText("Ganancias:");
        jPanel1.add(Ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        Costos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Costos.setText("Costos:");
        jPanel1.add(Costos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        Utilidades.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Utilidades.setText("Utilidades:");
        jPanel1.add(Utilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        Giones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Giones.setText("Guiones:");
        jPanel1.add(Giones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        Escenarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Escenarios.setText("Escenarios:");
        jPanel1.add(Escenarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        Animaciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Animaciones.setText("Animaciones:");
        jPanel1.add(Animaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        Doblajes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Doblajes.setText("Doblajes:");
        jPanel1.add(Doblajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        Drive.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Drive.setText("Drive");
        jPanel1.add(Drive, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        PlotTwist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlotTwist.setText("PlotTwist:");
        jPanel1.add(PlotTwist, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        ParaEntregar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ParaEntregar.setText("Capítulos a Entregar");
        jPanel1.add(ParaEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        Estandar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Estandar.setText("Estándar:");
        jPanel1.add(Estandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        Plot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plot.setText("PlotTwist:");
        jPanel1.add(Plot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        standardStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        standardStar.setText("0");
        standardStar.setToolTipText("");
        jPanel1.add(standardStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 70, -1));

        plottwistStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plottwistStar.setText("0");
        jPanel1.add(plottwistStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 70, -1));

        Supervision.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Supervision.setText("Supervisión");
        jPanel1.add(Supervision, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        Project.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Project.setText("Project Manager:");
        jPanel1.add(Project, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        projectStatusStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectStatusStar.setText("status");
        jPanel1.add(projectStatusStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, -1, -1));

        Director.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Director.setText("Director:");
        jPanel1.add(Director, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        directorStatusStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        directorStatusStar.setText("status");
        jPanel1.add(directorStatusStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        Faltas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Faltas.setText("Faltas");
        jPanel1.add(Faltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        projectFaultsStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectFaultsStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectFaultsStar.setText("0");
        jPanel1.add(projectFaultsStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 70, -1));

        Descuento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Descuento.setText("Descuento");
        jPanel1.add(Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, -1, -1));

        projectManagerDeductionStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectManagerDeductionStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectManagerDeductionStar.setText("0");
        jPanel1.add(projectManagerDeductionStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 210, -1));

        DiasRestantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DiasRestantes.setText("Días restantes:");
        jPanel1.add(DiasRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        deadlineCounterStar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deadlineCounterStar.setText("0");
        jPanel1.add(deadlineCounterStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 60, -1));

        Finanzas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Finanzas.setText("Nickelodeon");
        jPanel1.add(Finanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        plotStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plotStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        plotStorage.setText("/10");
        jPanel1.add(plotStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 90, -1));

        spriptStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spriptStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spriptStorage.setText("/25");
        jPanel1.add(spriptStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, -1));

        designerStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        designerStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        designerStorage.setText("/20");
        jPanel1.add(designerStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, -1));

        animatorStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        animatorStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        animatorStorage.setText("/55");
        jPanel1.add(animatorStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, -1));

        dubbingStorage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dubbingStorage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dubbingStorage.setText("/35");
        jPanel1.add(dubbingStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 90, -1));

        profit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profit.setText("0");
        jPanel1.add(profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 240, -1));

        earnings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        earnings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        earnings.setText("0");
        jPanel1.add(earnings, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 250, -1));

        costs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        costs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        costs.setText("0");
        jPanel1.add(costs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 260, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Duración de un día (segundos)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));
        jPanel1.add(simulationDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 71, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Deadline de los capítulos (días):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));
        jPanel1.add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 71, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Trabajadores:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Guionistas:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Diseñador de escenarios:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Animador de personajes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Actores de doblaje:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("PlotTwist:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Ensambladores:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));
        jPanel1.add(screenwriters, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 71, -1));
        jPanel1.add(stageDesigner, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 71, -1));
        jPanel1.add(animator, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 71, -1));
        jPanel1.add(voiceActors, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 71, -1));
        jPanel1.add(plotTwistScriptwriters, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 71, -1));
        jPanel1.add(assemblers, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 71, -1));

        saveButton1.setText("Guardar");
        jPanel1.add(saveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Timmy_Turner3.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nickpng.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -320, 1180, 950));

        jTabbedPane1.addTab("Nickelodeon", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 250, 58));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ganancias1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ganancias1.setText("Ganancias:");
        jPanel2.add(Ganancias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        Costos1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Costos1.setText("Costos:");
        jPanel2.add(Costos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        Utilidades1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Utilidades1.setText("Utilidades:");
        jPanel2.add(Utilidades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        Giones1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Giones1.setText("Guiones:");
        jPanel2.add(Giones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        Escenarios1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Escenarios1.setText("Escenarios:");
        jPanel2.add(Escenarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        Animaciones1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Animaciones1.setText("Animaciones:");
        jPanel2.add(Animaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        Doblajes1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Doblajes1.setText("Doblajes:");
        jPanel2.add(Doblajes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        Drive1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Drive1.setText("Drive");
        jPanel2.add(Drive1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        PlotTwist1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlotTwist1.setText("PlotTwist:");
        jPanel2.add(PlotTwist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        ParaEntregar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ParaEntregar1.setText("Capítulos a Entregar");
        jPanel2.add(ParaEntregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        Estandar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Estandar1.setText("Estándar:");
        jPanel2.add(Estandar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        Plot1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plot1.setText("PlotTwist:");
        jPanel2.add(Plot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        standardStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        standardStar1.setText("0");
        standardStar1.setToolTipText("");
        jPanel2.add(standardStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 70, -1));

        plottwistStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plottwistStar1.setText("0");
        jPanel2.add(plottwistStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 70, -1));

        Supervision1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Supervision1.setText("Supervisión");
        jPanel2.add(Supervision1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        Project1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Project1.setText("Project Manager:");
        jPanel2.add(Project1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        projectStatusStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectStatusStar1.setText("status");
        jPanel2.add(projectStatusStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, -1, -1));

        Director1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Director1.setText("Director:");
        jPanel2.add(Director1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        directorStatusStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        directorStatusStar1.setText("status");
        jPanel2.add(directorStatusStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        Faltas1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Faltas1.setText("Faltas");
        jPanel2.add(Faltas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        projectFaultsStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectFaultsStar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectFaultsStar1.setText("0");
        jPanel2.add(projectFaultsStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 70, -1));

        Descuento1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Descuento1.setText("Descuento");
        jPanel2.add(Descuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, -1, -1));

        projectManagerDeductionStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        projectManagerDeductionStar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectManagerDeductionStar1.setText("0");
        jPanel2.add(projectManagerDeductionStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 210, -1));

        DiasRestantes1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DiasRestantes1.setText("Días restantes:");
        jPanel2.add(DiasRestantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        deadlineCounterStar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deadlineCounterStar1.setText("0");
        jPanel2.add(deadlineCounterStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 60, -1));

        Finanzas1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Finanzas1.setText("Star Channel");
        jPanel2.add(Finanzas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        plotStorage1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plotStorage1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        plotStorage1.setText("/10");
        jPanel2.add(plotStorage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 90, -1));

        spriptStorage1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spriptStorage1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spriptStorage1.setText("/25");
        jPanel2.add(spriptStorage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, -1));

        designerStorage1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        designerStorage1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        designerStorage1.setText("/20");
        jPanel2.add(designerStorage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, -1));

        animatorStorage1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        animatorStorage1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        animatorStorage1.setText("/55");
        jPanel2.add(animatorStorage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, -1));

        dubbingStorage1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dubbingStorage1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dubbingStorage1.setText("/35");
        jPanel2.add(dubbingStorage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 90, -1));

        profit1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profit1.setText("0");
        jPanel2.add(profit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 240, -1));

        earnings1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        earnings1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        earnings1.setText("0");
        jPanel2.add(earnings1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 250, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Duración de un día (segundos)");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));
        jPanel2.add(simulationDuration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 71, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Deadline de los capítulos (días):");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));
        jPanel2.add(deadline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 71, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Trabajadores:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Guionistas:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Diseñador de escenarios:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Animador de personajes:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Actores de doblaje:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("PlotTwist:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Ensambladores:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));
        jPanel2.add(screenwriters1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 71, -1));
        jPanel2.add(stageDesigner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 71, -1));
        jPanel2.add(animator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 71, -1));
        jPanel2.add(voiceActors1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 71, -1));
        jPanel2.add(plotTwistScriptwriters1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 71, -1));
        jPanel2.add(assemblers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 71, -1));

        saveButton2.setText("Guardar");
        jPanel2.add(saveButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, -1, -1));

        SimpsonsText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image1.png"))); // NOI18N
        jPanel2.add(SimpsonsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        MargeSimpson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/star-header-2.png"))); // NOI18N
        jPanel2.add(MargeSimpson, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -90, 1180, 640));

        jTabbedPane1.addTab("Star Channel", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1179, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Animaciones;
    private javax.swing.JLabel Animaciones1;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Costos;
    private javax.swing.JLabel Costos1;
    private javax.swing.JLabel Descuento;
    private javax.swing.JLabel Descuento1;
    private javax.swing.JLabel DiasRestantes;
    private javax.swing.JLabel DiasRestantes1;
    private javax.swing.JLabel Director;
    private javax.swing.JLabel Director1;
    private javax.swing.JLabel Doblajes;
    private javax.swing.JLabel Doblajes1;
    private javax.swing.JLabel Drive;
    private javax.swing.JLabel Drive1;
    private javax.swing.JLabel Escenarios;
    private javax.swing.JLabel Escenarios1;
    private javax.swing.JLabel Estandar;
    private javax.swing.JLabel Estandar1;
    private javax.swing.JLabel Faltas;
    private javax.swing.JLabel Faltas1;
    private javax.swing.JLabel Finanzas;
    private javax.swing.JLabel Finanzas1;
    private javax.swing.JLabel Ganancias;
    private javax.swing.JLabel Ganancias1;
    private javax.swing.JLabel Giones;
    private javax.swing.JLabel Giones1;
    private javax.swing.JLabel MargeSimpson;
    private javax.swing.JLabel ParaEntregar;
    private javax.swing.JLabel ParaEntregar1;
    private javax.swing.JLabel Plot;
    private javax.swing.JLabel Plot1;
    private javax.swing.JLabel PlotTwist;
    private javax.swing.JLabel PlotTwist1;
    private javax.swing.JLabel Project;
    private javax.swing.JLabel Project1;
    private javax.swing.JLabel SimpsonsText;
    private javax.swing.JLabel Supervision;
    private javax.swing.JLabel Supervision1;
    private javax.swing.JLabel Utilidades;
    private javax.swing.JLabel Utilidades1;
    private javax.swing.JTextField animator;
    private javax.swing.JTextField animator1;
    private javax.swing.JLabel animatorStorage;
    private javax.swing.JLabel animatorStorage1;
    private javax.swing.JTextField assemblers;
    private javax.swing.JTextField assemblers1;
    private javax.swing.JLabel costs;
    private javax.swing.JTextField deadline;
    private javax.swing.JTextField deadline1;
    private javax.swing.JLabel deadlineCounterStar;
    private javax.swing.JLabel deadlineCounterStar1;
    private javax.swing.JLabel designerStorage;
    private javax.swing.JLabel designerStorage1;
    private javax.swing.JLabel directorStatusStar;
    private javax.swing.JLabel directorStatusStar1;
    private javax.swing.JLabel dubbingStorage;
    private javax.swing.JLabel dubbingStorage1;
    private javax.swing.JLabel earnings;
    private javax.swing.JLabel earnings1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel plotStorage;
    private javax.swing.JLabel plotStorage1;
    private javax.swing.JTextField plotTwistScriptwriters;
    private javax.swing.JTextField plotTwistScriptwriters1;
    private javax.swing.JLabel plottwistStar;
    private javax.swing.JLabel plottwistStar1;
    private javax.swing.JLabel profit;
    private javax.swing.JLabel profit1;
    private javax.swing.JLabel projectFaultsStar;
    private javax.swing.JLabel projectFaultsStar1;
    private javax.swing.JLabel projectManagerDeductionStar;
    private javax.swing.JLabel projectManagerDeductionStar1;
    private javax.swing.JLabel projectStatusStar;
    private javax.swing.JLabel projectStatusStar1;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton saveButton2;
    private javax.swing.JTextField screenwriters;
    private javax.swing.JTextField screenwriters1;
    private javax.swing.JTextField simulationDuration;
    private javax.swing.JTextField simulationDuration1;
    private javax.swing.JLabel spriptStorage;
    private javax.swing.JLabel spriptStorage1;
    private javax.swing.JTextField stageDesigner;
    private javax.swing.JTextField stageDesigner1;
    private javax.swing.JLabel standardStar;
    private javax.swing.JLabel standardStar1;
    private javax.swing.JTextField voiceActors;
    private javax.swing.JTextField voiceActors1;
    // End of variables declaration//GEN-END:variables
}
